"""empty message

Revision ID: 62abe7aa8088
Revises: a5c578322dea
Create Date: 2024-04-17 15:43:28.176104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62abe7aa8088'
down_revision = 'a5c578322dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
